### ISSUE TITLE
App deployment issue

### ISSUE THREAD

**Issue by dhruboroy29** [MukundanAtSamraksh/eMoteExt#2]
I created a [C# app](https://github.com/MukundanAtSamraksh/eMoteExt/tree/master/Extensions/ExampleLibApp) to test the ExampleLib interops (SHA: 4de3e23fad5e896e28dcae23cac7eb360d5ea83c). However, deployment with the custom built eMote seems to be failing deterministically with the message:
> An error has occurred.  Please check your hardware

I have reproduced this issue on two .NOWs so far. Current workaround:
1. Load [eMote 4.3.68](https://samraksh.com/index.php/support/emote-now-downloads)
2. Deploy ExampleLibApp
3. Load custom eMote (Solutions\EmoteDotNow\BuildOutput\Debug\bin\tinyclr.hex\ER_FLASH)

Output from a successful run with the above workaround:
```
Program found at 0x08020000
eMote OS v70
Platform EmoteDotNow
Based on Micro Framework v4.3.0.0
Build Date Aug 14 2018 13:23:55
Software ID: VCS not available during build.-ENOGIT by: mukun
GNU Compiler version 5.4.1
Optimization: speed-optimized, no-size-optimization
Clock nominal         :  8000000 Hz
Clock pre-calibration :  8016384 Hz
Clock post-calibration:  8016384 Hz
Starting...
Started Hardware.

Loading start at 8080168, end 8091b50
Assembly: mscorlib (4.3.1.0)
Assembly: Microsoft.SPOT.Native (4.3.1.0)
Assembly: Microsoft.SPOT.Hardware (4.3.1.0)
Assembly: Microsoft.SPOT.Update (4.3.1.0)
Assembly: MFUpdate (4.3.1.0)
Assembly: Microsoft.SPOT.Hardware.SerialPort (4.3.1.0)
Loading Deployment Assemblies.

Assembly: ExampleLib (1.0.0.0)
Assembly: ExampleLibApp (1.0.0.0) Resolving.
Ready.
Hello World!
One plus two = 3
Two plus four = 6
Addition with args: 5 plus 8 = 13
Done.
Waiting for debug commands...
```

**Comment by StudyKnowAdmire** [comment]
* My first guess is that the flash region memory layout still needs to be configured in a secondary code location (at Samraksh)— maybe the TinyCLR startup knows the app region start address, but the Debugger does not know the app region start address to pass to MFDeploy.  It is just TinyCLR being flashed, not TinyBooter, right?  
* My second guess is that the “static library” for the Debugger is missing or one of its dependencies is missing (Wire Protocol).  
* My third guess is the Debugger.dll on Windows PC does not match the Debugger component built with TinyCLR.  
* My fourth guess is that the newly linked TinyCLR ARM binary is missing the magic word (because it is not being built with MSBuild’s post-linker hooks?). 
* My fifth guess is it is an SREC preparation problem.

**Comment by mukundansridharan** [comment]
It was your second guess. The full debugger was not getting linked. Pushed a changed to correct a issue. Closing the issue.
